name: GitHub Hosted Runners

on:
  push:

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Show runner information
        run: |
          echo "OS: Ubuntu"
          echo "Hostname: $(hostname)"
          echo "User: $(whoami)"

  windows:
    runs-on: windows-latest

    steps:
      - name: Show runner information
        shell: bash
        run: |
          echo "OS: Windows"
          echo "Hostname: $(hostname)"
          echo "User: $(whoami)"

  macos:
    runs-on: macos-latest

    steps:
      - name: Show runner information
        run: |
          echo "OS: macOS"
          echo "Hostname: $(hostname)"
          echo "User: $(whoami)"